export const products = [
  {
    id: 1,
    title: "Wireless Headphones",
    price: 59.99,
    rating: 4.5,
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/51FNnHjzhQL._SL1200_.jpg",
    alt: "Wireless Headphones product image",
    description: "Experience high-quality audio with these sleek wireless headphones. Perfect for commuting, working out, or relaxing at home.",
  },
  {
    id: 2,
    title: "Stylish Backpack",
    price: 39.99,
    rating: 4.2,
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/41Esw-WhA7L.jpg",
    alt: "Stylish Backpack product image",
    description: "A durable and spacious backpack that combines functionality with modern style. Great for school, work, or travel.",
  },
  {
    id: 3,
    title: "Analog Men's Watch",
    price: 89.99,
    rating: 4.8,
    category: "Fashion",
    image: "https://m.media-amazon.com/images/I/51ykbSj-eoL._SX679_.jpg",
    alt: "Analog Men's Watch product image",
    description: "A classic analog watch with a stylish leather strap. Designed to complement both formal and casual outfits.",
  },
  {
    id: 4,
    title: "Gaming Mouse",
    price: 24.99,
    rating: 4.3,
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/41hYQ9J7gCL._SX300_SY300_QL70_FMwebp_.jpg",
    alt: "Gaming Mouse product image",
    description: "Boost your gaming performance with this high-precision mouse featuring customizable buttons and ergonomic design.",
  },
  {
    id: 5,
    title: "Casual T-Shirt",
    price: 14.99,
    rating: 4.0,
    category: "Fashion",
    image: "https://m.media-amazon.com/images/I/81FKfp-j0PL._SY879_.jpg",
    alt: "Casual T-Shirt product image",
    description: "Comfortable and breathable cotton t-shirt with a minimalist design. A staple piece for any casual wardrobe.",
  },
  {
    id: 6,
    title: "Bluetooth Speaker",
    price: 34.99,
    rating: 4.4,
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/71wAXhzCmnS._AC_UY436_FMwebp_QL65_.jpg",
    alt: "Bluetooth Speaker product image",
    description: "Compact and powerful speaker with deep bass and Bluetooth 5.0 for seamless connectivity anywhere.",
  },
  {
    id: 7,
    title: "Leather Wallet",
    price: 19.99,
    rating: 4.1,
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/61BygHH-M2L._AC_UL640_FMwebp_QL65_.jpg",
    alt: "Leather Wallet product image",
    description: "A sleek and minimal leather wallet with RFID protection and multiple card slots.",
  },
  {
    id: 8,
    title: "Running Shoes",
    price: 69.99,
    rating: 4.6,
    category: "Fashion",
    image: "https://m.media-amazon.com/images/I/61XwYMOyfwL._AC_UL640_FMwebp_QL65_.jpg",
    alt: "Running Shoes product image",
    description: "Lightweight and breathable shoes designed for maximum comfort during running or training.",
  },
  {
    id: 9,
    title: "Laptop Stand",
    price: 22.99,
    rating: 4.3,
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/51B4emQb6yL._AC_UY436_FMwebp_QL65_.jpg",
    alt: "Laptop Stand product image",
    description: "Aluminum adjustable laptop stand that improves posture and airflow for better performance.",
  },
  {
    id: 10,
    title: "Sunglasses",
    price: 29.99,
    rating: 4.0,
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/41Dr9I4x1EL._AC_UL640_FMwebp_QL65_.jpg",
    alt: "Sunglasses product image",
    description: "UV-protected stylish sunglasses perfect for summer outings and driving.",
  },
  {
  id: 11,
  title: "Fitness Smartwatch",
  price: 74.99,
  rating: 4.7,
  category: "Electronics",
  image: "https://m.media-amazon.com/images/I/61rmkmqD5VL._AC_UY436_FMwebp_QL65_.jpg",
  alt: "Fitness Smartwatch product image",
  description: "Track your steps, heart rate, sleep, and notifications with this stylish fitness smartwatch.",
},
{
  id: 12,
  title: "Travel Duffel Bag",
  price: 45.00,
  rating: 4.3,
  category: "Accessories",
  image: "https://m.media-amazon.com/images/I/71-8gqDAalL._AC_UL640_FMwebp_QL65_.jpg",
  alt: "Travel Duffel Bag product image",
  description: "Spacious and durable duffel bag perfect for weekend trips, gym sessions, or daily use.",
},
{
  id: 13,
  title: "Denim Jacket",
  price: 59.50,
  rating: 4.4,
  category: "Fashion",
  image: "https://m.media-amazon.com/images/I/815DHwdwDaL._AC_UL640_FMwebp_QL65_.jpg",
  alt: "Denim Jacket product image",
  description: "Classic denim jacket with a modern fit. Adds rugged style to any casual outfit.",
},
{
  id: 14,
  title: "Wireless Keyboard & Mouse Combo",
  price: 28.75,
  rating: 4.2,
  category: "Electronics",
  image: "https://m.media-amazon.com/images/I/61ZvJw9wlXL._AC_UY436_FMwebp_QL65_.jpg",
  alt: "Wireless Keyboard and Mouse product image",
  description: "Slim, ergonomic wireless combo ideal for home or office setups with long battery life.",
},
{
  id: 15,
  title: "Leather Belt",
  price: 18.99,
  rating: 4.1,
  category: "Accessories",
  image: "https://m.media-amazon.com/images/I/71hEGHI6AnL._AC_UL640_FMwebp_QL65_.jpg",
  alt: "Leather Belt product image",
  description: "Durable genuine leather belt suitable for both formal and casual wear.",
}

];
