export const products = [
  {
    id: 1,
    title: "Wireless Headphones",
    price: 59.99,
    rating: 4.5,
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/51FNnHjzhQL._SL1200_.jpg",
    alt: "Wireless Headphones product image",
    description: "Experience high-quality audio with these sleek wireless headphones. Perfect for commuting, working out, or relaxing at home.",
  },
  {
    id: 2,
    title: "Stylish Backpack",
    price: 39.99,
    rating: 4.2,
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/41Esw-WhA7L.jpg",
    alt: "Stylish Backpack product image",
    description: "A durable and spacious backpack that combines functionality with modern style. Great for school, work, or travel.",
  },
  {
    id: 3,
    title: "Analog Men's Watch",
    price: 89.99,
    rating: 4.8,
    category: "Fashion",
    image: "https://m.media-amazon.com/images/I/51ykbSj-eoL._SX679_.jpg",
    alt: "Analog Men's Watch product image",
    description: "A classic analog watch with a stylish leather strap. Designed to complement both formal and casual outfits.",
  },
  {
    id: 4,
    title: "Gaming Mouse",
    price: 24.99,
    rating: 4.3,
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/41hYQ9J7gCL._SX300_SY300_QL70_FMwebp_.jpg",
    alt: "Gaming Mouse product image",
    description: "Boost your gaming performance with this high-precision mouse featuring customizable buttons and ergonomic design.",
  },
  {
    id: 5,
    title: "Casual T-Shirt",
    price: 14.99,
    rating: 4.0,
    category: "Fashion",
    image: "https://m.media-amazon.com/images/I/81FKfp-j0PL._SY879_.jpg",
    alt: "Casual T-Shirt product image",
    description: "Comfortable and breathable cotton t-shirt with a minimalist design. A staple piece for any casual wardrobe.",
  },
];
